# Frontend Dockerfile
FROM node:20
WORKDIR /frontend/
COPY package.json /frontend/package.json
RUN npm install
COPY ./tsconfig.json ./tailwind.config.js postcss.config.js tsconfig.app.json ./tsconfig.node.json ./vite.config.ts ./index.html /frontend/
COPY ./src/ /frontend/src/
COPY ./public/ /frontend/public/
CMD ["npm", "run", "dev", "--", "--host"]
